### update user
PATCH http://localhost:3000/users/update/2
Content-Type: application/json

{
    "email": "tola@gmail.com",
    "password": "tola"
}

### create user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "toi@gmail.com",
    "password": "pass//"
}
#### Sign In
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "toi@gmail.com",
    "password": "pass//"
}

### sign out
POST http://localhost:3000/users/signout

### who am i
GET http://localhost:3000/users/whoami

### delete user
DELETE http://localhost:3000/users/del/11

### delete all user
DELETE http://localhost:3000/users/delall

### findAll
GET http://localhost:3000/users/findAll

### findOne
GET http://localhost:3000/users/find/18

