### update user
PATCH http://localhost:3000/users/update/2
Content-Type: application/json

{
    "email": "tola@gmail.com",
    "password": "124"
}

### create user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "User@gmail.com",
    "password": "User"
}
#### Sign In Admin
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "admin"
}

### Sign in User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test"
}

### sign out
POST http://localhost:3000/users/signout

### who am i
GET http://localhost:3000/auth/whoami

### delete user
DELETE http://localhost:3000/users/del/11

### delete all user
DELETE http://localhost:3000/users/delall

### findAll
GET http://localhost:3000/users/findAll

### findOne
GET http://localhost:3000/users/find/18

-------------------------------------------------------------------------------------------------

### Create adoption
POST http://localhost:3000/adoptions/create
Content-Type: application/json

{
    "pokemonId": 1
}

### Get pending adoptions
GET http://localhost:3000/adoptions/pending

### Get approved adoptions
GET http://localhost:3000/adoptions/approve

### Get rejected adoptions
GET http://localhost:3000/adoptions/reject

### Get one adoption by id
GET http://localhost:3000/adoptions/1

### Approve adoption
PUT http://localhost:3000/adoptions/1/approve
Content-Type: application/json

{}

### Reject adoption
PUT http://localhost:3000/adoptions/1/reject
Content-Type: application/json

{
    "reason": "Le formulaire est incomplet"
}
